version: "3.5"
services:
  temporal:
    environment:
      - PROMETHEUS_ENDPOINT=0.0.0.0:8000
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - type: bind
        source: ./deployment/prometheus/config.yml
        target: /etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    build: './deployment/grafana'
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - 8085:3000
    volumes:
      - type: bind
        source: ./deployment/grafana/provisioning/datasources
        target: /etc/grafana/provisioning/datasources
  mailhog:
    image: mailhog/mailhog:v1.0.1
    command: -invite-jim
    ports:
      - 8025:8025
  api:
    build: .
    command: bgc-backend api
    restart: unless-stopped
    environment:
      - TEMPORAL_GRPC_ENDPOINT=temporal:7233
  thirdparty:
    build: .
    command: thirdparty-simulator api
    restart: unless-stopped
    environment:
      - TEMPORAL_GRPC_ENDPOINT=temporal:7233
  worker:
    build: .
    command: bgc-backend worker
    restart: unless-stopped
    environment:
      - TEMPORAL_GRPC_ENDPOINT=temporal:7233
  tools:
    build: .
    command: tail -f /dev/null
    environment:
      - TEMPORAL_CLI_ADDRESS=temporal:7233
  ui:
    build: .
    command: bgc-backend ui
    restart: unless-stopped
    ports:
      - 8083:8083
  dataconverter:
    build: .
    command:
      tctl dc web --web_ui_url http://localhost:8088
    restart: unless-stopped
    ports:
      - 8086:8086
    environment:
      - TEMPORAL_CLI_ADDRESS=temporal:7233
      - TEMPORAL_CLI_DATA_CONVERTER_PORT=8086